version: 2
jobs:
  build:
    working_directory: /go/src/github.com/nbio/hitch
    docker:
      - image: golang:1.9
    steps:
      - checkout
      - run:
          name: Install JUnit
          command: go get -v -t -u -f github.com/jstemmer/go-junit-report
      - run:
          name: go get
          command: go get -t -d -v ./...
      - run:
          name: go build
          command: go build -v
      - run: mkdir -p ~/junit
      - run:
          name: Run unit tests
          command: (set -o pipefail && go test -v ./... -race | go-junit-report > ~/junit/whois.xml)
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
